### ISSUE TITLE
Member skills not updating

### ISSUE THREAD

**Issue by tyler274** [evecm/ecm#13]
ECM isn't pulling members skills (all apis are full apis), not throwing any errors on the scheduled tasks either. 

Any clue? 

Thanks once again

**Comment by tyler274** [comment]
In debug mode and running through each related tasks with the logs tailed now

**Comment by ggrog** [comment]
Make sure the characters are "associated", then run the update_all_character_associations task.

**Comment by tyler274** [comment]
thank you that was it, i had some bad apis that were lingering from our auth system (I imported them into ecm) and were causing the association to fail.

**Comment by ggrog** [comment]
No prob.  Btw I'm in game @ Grog Maken if you need more help, I'll idle there today.
