### ISSUE TITLE
IntegrityError

### ISSUE THREAD

**Issue by Dharr-Guartonzec** [evecm/ecm#18]
Environment:

Django Version: 1.5.7
Python Version: 2.7.5

Exception Type: IntegrityError at /
Exception Value: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`ecm`.`industry_supply`, CONSTRAINT `supply_source_id_refs_location_id_800eb96f` FOREIGN KEY (`supply_source_id`) REFERENCES `industry_supplysource` (`location_id`))')

I'm getting a 500 Internal Server error, so i activated the Debug option i settings.ini file.

Any idea?

**Comment by UnderMyBed** [comment]
Can you post the contents of the error.log file in the <install_dir>/logs folder? I think you are getting error 500 from something else. I would also turn off debug mode since that isn't going to be much help here.

**Comment by ggrog** [comment]
What DB backend are you using? What version of ecm are you running? What static DB file did you use to initialize your instance?

**Comment by Dharr-Guartonzec** [comment]
The "error.log" file is empty, also the ecm one is. 

I used the http://www.ggrog.com/scylla.mysql.bz2 DB file to initialize and i use MariaDB on Centos 7.

Maria DB is :mariadb-server-5.5.41-2.el7_0.x86_64, same are the devel files for it. ECM was installed via PIP so should be the recent version i assume. But also an upgrade via git to current github release did not work. The progress always stops with:

"Running migrations for industry:
 - Migrating forwards to 0004_del_field_invention_chance.
 > industry:0002_industry_data
 - Migration 'industry:0002_industry_data' is marked for no-dry-run.
 ! Error found during real run of migration! Aborting.

 ! Since you have a database that does not support running
 ! schema-altering statements in transactions, we have had
 ! to leave it in an interim state between migrations.

! You *might* be able to recover with:   (migration cannot be dry-run; cannot discover commands)
 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: industry:0002_industry_data
DeserializationError: Problem installing fixture '/usr/lib/python2.7/site-packages/ecm/plugins/industry/fixtures/0002_industry_data.json': InventionPolicy has no field named u'base_invention_chance'"

i turned off Debug now.

**Comment by ggrog** [comment]
Dharr,
I was able to reproduce the error on my end with a brand new installation of ECM.  There's a bug that only affects new 2.2.2 installs, so I was missing it when I was doing upgrades.

To fix, please run:
`pip install ecm==2.2.2b`
`ecm-admin init /var/www/your-site-name`
This second command is picking up the install process from https://github.com/evecm/ecm/wiki/CentOS-Install-Quick-Guide#initialize-the-instance .  Please continue from there.

Sorry for the trouble!
