### ISSUE TITLE
Installation Migration issue.

### ISSUE THREAD

**Issue by victorsai** [evecm/ecm#23]
CentOS 7.0.1406
Python 2.7.5
Django 1.5.7

When running ecm-admin init, this happens

[ECM] Initializing database...
[ECM] $ /bin/python manage.py syncdb --noinput --migrate
.....
Running migrations for industry:
 - Migrating forwards to 0004_del_field_invention_chance.
 > industry:0002_industry_data
 - Migration 'industry:0002_industry_data' is marked for no-dry-run.
 ! Error found during real run of migration! Aborting.

 ! Since you have a database that does not support running
 ! schema-altering statements in transactions, we have had
 ! to leave it in an interim state between migrations.

! You *might* be able to recover with:   (migration cannot be dry-run; cannot discover commands)
 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: industry:0002_industry_data
DeserializationError: Problem installing fixture '/usr/lib/python2.7/site-packages/ecm/plugins/industry/fixtures/0002_industry_data.json': InventionPolicy has no field named u'base_invention_chance'

**Comment by ggrog** [comment]
This has been fixed for awhile, you must not have the latest ECM, 2.2.3.1.  Run ```pip install --upgrade ecm``` and try again.

**Comment by victorsai** [comment]
I thought I had the latest version.  Upgrading fixed it.  Thank you.

**Comment by ggrog** [comment]
You're welcome.
