### ISSUE TITLE
Captcha not working

### ISSUE THREAD

**Issue by Dharr-Guartonzec** [evecm/ecm#29]
# tail -f error.log
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 42, in __getattr__

ImportError: The _imagingft C module is not installed
2015-09-04 15:00:47,589 [ERROR] django.request - Internal Server Error: /captcha/image/38753853a70df9b24fcd2860559760055612f1bb/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in get_response
    except: # Any exception should be gathered and handled
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/locale.py", line 29, in process_response
    if (response.status_code == 404 and
AttributeError: 'NoneType' object has no attribute 'status_code'

Any idea? I'm pretty sure all dependencies got installed.

**Comment by ggrog** [comment]
Install libfreetype-dev and then reinstall (recompile) PIL.

Refer to http://stackoverflow.com/a/5770215

**Comment by Dharr-Guartonzec** [comment]
I've done all that already. And PIL(low) reports back JPEG support is available:

--------------------------------------------------------------------
PIL SETUP SUMMARY
--------------------------------------------------------------------
version      Pillow 2.9.0
platform     linux2 2.7.6 (default, Jun 22 2015, 17:58:13)
             [GCC 4.8.2]
--------------------------------------------------------------------
--- TKINTER support available
--- JPEG support available
*** OPENJPEG (JPEG2000) support not available
--- ZLIB (PNG/ZIP) support available
--- LIBTIFF support available
--- FREETYPE2 support available
--- LITTLECMS2 support available
--- WEBP support available
--- WEBPMUX support available
--------------------------------------------------------------------

**Comment by ggrog** [comment]
In your first message it's clear django is using PIL, not pillow:
*/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py*

Try:
pip uninstall PIL # note the case sensitivity

**Comment by Dharr-Guartonzec** [comment]
Hum..... 

# pip uninstall PIL
Cannot uninstall requirement PIL, not installed
#

---

# pip install PIL --upgrade
Collecting PIL
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement PIL (from versions: )
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external PIL to allow).
No matching distribution found for PIL
#

So only an untrusted PIL version can be used. Besides that i found out at least on Ubunti hear upper or lowecase natation doesn't matter. That can
t be the issue.

**Comment by Dharr-Guartonzec** [comment]
I followed this here now:

**Comment by Dharr-Guartonzec** [comment]
Damn it! A reload of the apache server instance fixed the issue. my bad.
