### ISSUE TITLE
Developer Documentation

### ISSUE THREAD

**Issue by narthollis** [evecm/ecm#33]
Given that this project is somewhat non-standard for a Django project it would be useful to have some developer documentation. 

I recall that the old ECM website used to have some documentation for getting setup as a developer, however I am currently unable to access the old website to retrieve this documentation.

Given the inaccessibility of the old website, I think it would be useful to have some developer documentation on the wiki here on GitHub.

**Comment by ggrog** [comment]
I put up a mirror of the old website here: http://redmine.ggrog.com/projects/ecm/wiki

It's my intention to port over the relevant old wiki pages here.

**Comment by narthollis** [comment]
Excellent. Thanks muchly.
