### ISSUE TITLE
Use Celery Workers instead of Cron Tasks

### ISSUE THREAD

**Issue by narthollis** [evecm/ecm#34]
The [Celery project](http://www.celeryproject.org/) is an asynchronous task framework for python, that integrates well with Django.

It has been used well in the [EVEThing](https://github.com/madcowfred/evething) as for its task backend.

This would allow for the project to behave better for mid sized corporations(>100 character APIs) and to be able to scale up well to very large corporations.

**Comment by narthollis** [comment]
I have plans to work on this myself, and opened this issue so that the idea of using celery as the task framework can be discussed before I submit a pull request.

My current thinking is to break the background tasks down into 2 basic categories:
- API Calls
- Database interaction.

The idea here being the ability to push API calls off onto servers that have no direct access to the real ECM database. The API call tasks will take all necessary parameters, make the call to the API server and then return the result by the Celery message bus.

The Database Interaction tasks will trigger the API calls, perform any necessary data processing on the returned data and submit this data back to the database.
The Database Interaction tasks are also where the tasks responsible for performing user maintenance such as sending our emails for broken, or missing API keys or other alerts and notifications.

**Comment by ggrog** [comment]
Sounds like a good idea to me.  All that I ask is that you *try* to keep the existing "tasks" + cron architecture for backward compatibility and as a lightweight option.  If not, I understand, but hopefully it's possible.

**Comment by narthollis** [comment]
Yeah, that seams like a reasonable request.

I have an idea on how I may be able to do this, but I will need to test it out to be sure.
