### ISSUE TITLE
Problem importing galatea data

### ISSUE THREAD

**Issue by narthollis** [evecm/ecm#35]
I am running a PostgreSQL 9.4 database and have tried both the JSON and PostgreSQL dumps from ggrog.com.

    (ecm) D:\Users\narthollis\workspace>ecm-admin load ecm-dev-site D:\Users\narthollis\Downloads\galatea.json
    [ECM] Importing 'D:\\Users\\narthollis\\Downloads\\galatea.json'... (this may take awhile!)
    [ECM] $ C:\Users\narthollis\virtenvs\ecm\Scripts\python.exe manage.py loaddata c:\users\nartho~1\appdata\local\temp\tmpa4mwve\temp.json
    IntegrityError: Problem installing fixtures: insert or update on table "eve_type" violates foreign key constraint "marketGroupID_refs_marketGroupID_a2ded217"
    DETAIL:  Key (marketGroupID)=(354496) is not present in table "eve_marketgroup".

I am currently using the Carnyx dump as the Aegis dump also failed with a different error.

**Comment by ggrog** [comment]
galatea.pgsql.bz2 works for me (PG 9.1).  Can you manually load the .sql? Then you should get a good error message.
```
# su to appropriate postgres user as needed
wget http://www.ggrog.com/galatea.pgsql.bz2
bunzip2 galatea.pgsql.bz2
psql -d yourDB -f galatea.pgsql
```

**Comment by ggrog** [comment]
Regarding the JSON, those files are loaded with foreign key relations enabled so any DB inconsistencies break things.  :ccp:  I will add a line in my conversion script to delete the offending row.

**Comment by ggrog** [comment]
Ok, posted new dumps to http://www.ggrog.com/ (`galatea2.*`) and updated the conversion script.  Thanks for the report, I'll reopen if there are further issues.
