### ISSUE TITLE
Issue in the dependencies for the setuptools

### ISSUE THREAD

**Issue by bllevy2** [evecm/ecm#42]
There is an issue with the dependencies
dependencies = [
    'django_simple_captcha >= 0.3',
    'south == 0.8',
    'django_compressor == 1.1.2',
    'setuptools',
    'django <= 1.5.7',
    'pytz',
    'pycrypto',
]

this is broken as of django_simple_captcha 0.5.1 because it requires django 1.7(took me way to long to figure that one out). I currently  switched it to require 'django_simple_captcha < 0.4.0' but felt that it would be better if a curator of the project determined what version was correct and update the dependency to set that. In the long term the project should probably be migrated to a higher version of django but as it is my change fixed the issue in the ecm-admin tool.

**Comment by i5okie** [comment]
were you able to install and run ecm after your modification?
I got it installed. But get a bunch of httpd errors in the log with a 500 server error.
