### ISSUE TITLE
New data for YC118-3?

### ISSUE THREAD

**Issue by Gavin-Tremlor** [evecm/ecm#44]
Looking for the latest data dump, dated March 9 2016.  Where can I find it?  The -f option throws an error, ERROR 1062 (23000) at line 64: Duplicate entry '21527' for key 'PRIMARY'

Thanks.

**Comment by ggrog** [comment]
Hi, in typical CCP fashion they have stuff in almost every DB update that
breaks things. I'm on vacation right now so it will be another day or two
yet but I'll get it fixed. Thanks for the report.
